services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
